### ISSUE TITLE
Add more docs to the readme

### ISSUE THREAD

**Issue by Ahmed-Ayman** [Vardot/vartheme_bs4#2]
Currently the Readme has no instructions at all, I will add some more useful instructions to make things a little easier for the new comers.

**Comment by Natshah** [comment]
Thank you Ahmed for reporting
Updated in
https://docs.varbase.vardot.com/dev-docs/theme-development-with-varbase/creating-your-own-theme
https://github.com/Vardot/vartheme_bs4/tree/9.0.x/scripts
